apiVersion: v1
kind: Service
metadata:
  name: pub-hub
  annotations:
    maesh.containo.us/traffic-type: http
spec:
  ports:
  - port: 80
    targetPort: 7777
  selector:
    app: pub-hub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub-hub
spec:
  selector:
    matchLabels:
      app: pub-hub
  replicas: 2
  template:
    metadata:
      labels:
        app: pub-hub
    spec:
      containers:
      - name: pub-hub
        image: "charlesdburton/grillbernetes-pub-hub:latest"
        args:
        - "-nh=nats://nats-cluster:4222"
        - "-rd=redis:6379"
        ports:
        - containerPort: 7777
        imagePullPolicy: Always
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pub-hub
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  tls:
  - hosts:
    - pub-hub.home.rsmachiner.com
    secretName: pub-hub
  rules:
  - host: pub-hub.home.rsmachiner.com
    http:
      paths:
      - backend:
          serviceName: pub-hub
          servicePort: 80