apiVersion: v1
kind: Service
metadata:
  name: control-hub
  annotations:
    maesh.containo.us/traffic-type: http
spec:
  ports:
  - port: 80
    targetPort: 7777
  selector:
    app: control-hub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-hub
spec:
  selector:
    matchLabels:
      app: control-hub
  replicas: 2
  template:
    metadata:
      labels:
        app: control-hub
    spec:
      containers:
      - name: control-hub
        image: "charlesdburton/grillbernetes-control-hub:latest"
        args:
        - "-rd=redis-cluster:6379"
        ports:
        - containerPort: 7777
        imagePullPolicy: Always
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-redirect-control-hub
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`control-hub.home.rsmachiner.com`)
      kind: Rule
      services:
        - name: control-hub
          port: 80
      middlewares:
        - name: redirect
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls-control-hub
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`control-hub.home.rsmachiner.com`)
    kind: Rule
    services:
    - name: control-hub
      port: 80
  tls:
    certResolver: default