apiVersion: v1
kind: Service
metadata:
  name: control-hub
spec:
  ports:
  - port: 80
    targetPort: 7777
  selector:
    app: control-hub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-hub
spec:
  selector:
    matchLabels:
      app: control-hub
  replicas: 3
  template:
    metadata:
      labels:
        app: control-hub
    spec:
      containers:
      - name: control-hub
        image: "charlesdburton/control-hub-arm64:latest"
        args:
        - "-nh=nats://nats-cluster:4222"
        ports:
        - containerPort: 7777
        imagePullPolicy: Always

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: control-hub-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-control-hub
spec:
  tls:
  - hosts:
    - control-hub.home.rsmachiner.com
    secretName: letsencrypt-control-hub
  rules:
  - host: control-hub.home.rsmachiner.com
    http:
      paths:
      - path: /send
        backend:
          serviceName: control-hub
          servicePort: 80
