apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- auth-service.yaml
- control-hub.yaml
- events.yaml
- pub-hub.yaml
images:
- name: charlesdburton/grillbernetes-auth-service:latest
  newName: charlesdburton/grillbernetes-auth-service
  newTag: 7d732d9c63407f35736169724dc7255bcf4c32c1
- name: charlesdburton/grillbernetes-control-hub:latest
  newName: charlesdburton/grillbernetes-control-hub
  newTag: 7d732d9c63407f35736169724dc7255bcf4c32c1
- name: charlesdburton/grillbernetes-events:latest
  newName: charlesdburton/grillbernetes-events
  newTag: 7d732d9c63407f35736169724dc7255bcf4c32c1
- name: charlesdburton/grillbernetes-pub-hub:latest
  newName: charlesdburton/grillbernetes-pub-hub
  newTag: 7d732d9c63407f35736169724dc7255bcf4c32c1
