apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- auth-service.yaml
- control-hub.yaml
- events.yaml
- pub-hub.yaml
images:
- name: charlesdburton/grillbernetes-auth-service:latest
  newName: charlesdburton/grillbernetes-auth-service
  newTag: 2b6d42c0a3d1b6a584449e14bef81d9a47a6be19
- name: charlesdburton/grillbernetes-control-hub:latest
  newName: charlesdburton/grillbernetes-control-hub
  newTag: 2b6d42c0a3d1b6a584449e14bef81d9a47a6be19
- name: charlesdburton/grillbernetes-events:latest
  newName: charlesdburton/grillbernetes-events
  newTag: 2b6d42c0a3d1b6a584449e14bef81d9a47a6be19
- name: charlesdburton/grillbernetes-pub-hub:latest
  newName: charlesdburton/grillbernetes-pub-hub
  newTag: 2b6d42c0a3d1b6a584449e14bef81d9a47a6be19
