apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- auth-service.yaml
- control-hub.yaml
- events.yaml
- pub-hub.yaml
images:
- name: charlesdburton/grillbernetes-auth-service:latest
  newName: charlesdburton/grillbernetes-auth-service
  newTag: a66a15cc279e9cd6cb29c35c5ed405596a9d1bbd
- name: charlesdburton/grillbernetes-control-hub:latest
  newName: charlesdburton/grillbernetes-control-hub
  newTag: a66a15cc279e9cd6cb29c35c5ed405596a9d1bbd
- name: charlesdburton/grillbernetes-events:latest
  newName: charlesdburton/grillbernetes-events
  newTag: a66a15cc279e9cd6cb29c35c5ed405596a9d1bbd
- name: charlesdburton/grillbernetes-pub-hub:latest
  newName: charlesdburton/grillbernetes-pub-hub
  newTag: a66a15cc279e9cd6cb29c35c5ed405596a9d1bbd
