apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- auth-service.yaml
- control-hub.yaml
- events.yaml
- pub-hub.yaml
- stream-manager.yaml
images:
- name: charlesdburton/grillbernetes-auth-service:latest
  newName: charlesdburton/grillbernetes-auth-service
  newTag: 4cf598251c5cfcd6acf744604b3b3e966f49de88
- name: charlesdburton/grillbernetes-control-hub:latest
  newName: charlesdburton/grillbernetes-control-hub
  newTag: 4cf598251c5cfcd6acf744604b3b3e966f49de88
- name: charlesdburton/grillbernetes-events:latest
  newName: charlesdburton/grillbernetes-events
  newTag: 4cf598251c5cfcd6acf744604b3b3e966f49de88
- name: charlesdburton/grillbernetes-pub-hub:latest
  newName: charlesdburton/grillbernetes-pub-hub
  newTag: 4cf598251c5cfcd6acf744604b3b3e966f49de88
- name: charlesdburton/grillbernetes-stream-manager:latest
  newName: charlesdburton/grillbernetes-stream-manager
  newTag: 4cf598251c5cfcd6acf744604b3b3e966f49de88
