apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- auth-service.yaml
- control-hub.yaml
- events.yaml
- pub-hub.yaml
- stream-manager.yaml
images:
- name: charlesdburton/grillbernetes-auth-service:latest
  newName: charlesdburton/grillbernetes-auth-service
  newTag: 1fddd7a21bf78fb996c016e11a45e574f38ec712
- name: charlesdburton/grillbernetes-control-hub:latest
  newName: charlesdburton/grillbernetes-control-hub
  newTag: 1fddd7a21bf78fb996c016e11a45e574f38ec712
- name: charlesdburton/grillbernetes-events:latest
  newName: charlesdburton/grillbernetes-events
  newTag: 1fddd7a21bf78fb996c016e11a45e574f38ec712
- name: charlesdburton/grillbernetes-pub-hub:latest
  newName: charlesdburton/grillbernetes-pub-hub
  newTag: 1fddd7a21bf78fb996c016e11a45e574f38ec712
- name: charlesdburton/grillbernetes-stream-manager:latest
  newName: charlesdburton/grillbernetes-stream-manager
  newTag: 1fddd7a21bf78fb996c016e11a45e574f38ec712
