apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- auth-service.yaml
- control-hub.yaml
- events.yaml
- pub-hub.yaml
- stream-manager.yaml
images:
- name: charlesdburton/grillbernetes-auth-service:latest
  newName: charlesdburton/grillbernetes-auth-service
  newTag: f67b96588f80be8e56747e12ae4c5c4b36cfa8ca
- name: charlesdburton/grillbernetes-control-hub:latest
  newName: charlesdburton/grillbernetes-control-hub
  newTag: f67b96588f80be8e56747e12ae4c5c4b36cfa8ca
- name: charlesdburton/grillbernetes-events:latest
  newName: charlesdburton/grillbernetes-events
  newTag: f67b96588f80be8e56747e12ae4c5c4b36cfa8ca
- name: charlesdburton/grillbernetes-pub-hub:latest
  newName: charlesdburton/grillbernetes-stream-manager
  newTag: f67b96588f80be8e56747e12ae4c5c4b36cfa8ca
- name: charlesdburton/grillbernetes-stream-manager:latest
  newName: charlesdburton/grillbernetes-stream-manager
  newTag: d35c40780ff1abc14688a9161b3be40e7774c219
