// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Device struct {
	Device      string `json:"device"`
	TimeSeconds int    `json:"time_seconds"`
	Channel     string `json:"channel"`
}

type Login struct {
	Email        string  `json:"email"`
	Password     *string `json:"password"`
	AccessToken  *string `json:"accessToken"`
	RefreshToken *string `json:"refreshToken"`
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SendData struct {
	ID    string  `json:"id"`
	Token string  `json:"token"`
	Type  *string `json:"type"`
}

type User struct {
	ID           string  `json:"id"`
	Email        string  `json:"email"`
	AccessToken  *string `json:"accessToken"`
	RefreshToken *string `json:"refreshToken"`
}

type Username struct {
	Username string `json:"username"`
}
