apiVersion: v1
kind: Service
metadata:
  name: events
spec:
  ports:
  - port: 80
    targetPort: 7777
  selector:
    app: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
spec:
  selector:
    matchLabels:
      app: events
  replicas: 1
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
      - name: events
        image: "charlesdburton/grillbernetes-events:latest"
        args:
        - "-nh=nats://nats-cluster:4222"
        ports:
        - containerPort: 7777
        imagePullPolicy: Always

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: events-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-events
spec:
  tls:
  - hosts:
    - grillbernetes.home.rsmachiner.com
    secretName: letsencrypt-events
  rules:
  - host: grillbernetes.home.rsmachiner.com
    http:
      paths:
      - path: /
        backend:
          serviceName: events
          servicePort: 80

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-events
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "charles.d.burton@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-events
    http01: {}

