apiVersion: v1
kind: Service
metadata:
  name: events
spec:
  ports:
  - port: 80
    targetPort: 7777
  selector:
    app: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
spec:
  selector:
    matchLabels:
      app: events
  replicas: 1
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
      - name: events
        image: "charlesdburton/grillbernetes-events:arm64"
        args:
        - "-nh=nats://nats-cluster:4222"
        ports:
        - containerPort: 7777
        imagePullPolicy: Always
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-redirect-events
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`events.home.rsmachiner.com`)
      kind: Rule
      services:
        - name: events
          port: 80
      middlewares:
        - name: redirect
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls-events
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`events.home.rsmachiner.com`)
    kind: Rule
    services:
    - name: events
      port: 80
  tls:
    certResolver: default