name: ControlHubBuild

on:
  push:
    branches:
    - master

jobs:
  control-hub-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of control-hub
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        working-directory: control-hub
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-control-hub:arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-control-hub:arm
  control-hub-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of control-hub
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        working-directory: control-hub
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-control-hub:arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-control-hub:arm64
  control-hub-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of control-hub
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        working-directory: control-hub
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-control-hub:amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-control-hub:amd64
  control-hub-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push
    needs: ["control-hub-build-arm", "control-hub-build-arm64", "control-hub-build-amd64"]
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create charlesdburton/grillbernetes-control-hub:latest \
          charlesdburton/grillbernetes-control-hub:amd64 \
          charlesdburton/grillbernetes-control-hub:arm \
          charlesdburton/grillbernetes-control-hub:arm64 
      - name: Annotate Arm
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm charlesdburton/grillbernetes-control-hub:latest charlesdburton/grillbernetes-control-hub:arm
      - name: Annotate Arm64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm64 charlesdburton/grillbernetes-control-hub:latest charlesdburton/grillbernetes-control-hub:arm64
      - name: Annotate AMD64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch amd64 charlesdburton/grillbernetes-control-hub:latest charlesdburton/grillbernetes-control-hub:amd64
      - name: Push Manifest
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push charlesdburton/grillbernetes-control-hub:latest