name: GrillbernetesBuild

on:
  push:
    branches:
    - master

jobs:
  pub-hub-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of pub-hub
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        working-directory: pub-hub
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-pub-hub:arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-pub-hub:arm
  pub-hub-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of pub-hub
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        working-directory: pub-hub
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-pub-hub:arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-pub-hub:arm64
  pub-hub-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of pub-hub
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        working-directory: pub-hub
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-pub-hub:amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-pub-hub:amd64
  pub-hub-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push
    needs: ["pub-hub-build-arm", "pub-hub-build-arm64", "pub-hub-build-amd64"]
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create charlesdburton/grillbernetes-pub-hub:latest \
          charlesdburton/grillbernetes-pub-hub:amd64 \
          charlesdburton/grillbernetes-pub-hub:arm \
          charlesdburton/grillbernetes-pub-hub:arm64 
      - name: Annotate Arm
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm charlesdburton/grillbernetes-pub-hub:latest charlesdburton/grillbernetes-pub-hub:arm
      - name: Annotate Arm64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm64 charlesdburton/grillbernetes-pub-hub:latest charlesdburton/grillbernetes-pub-hub:arm64
      - name: Annotate AMD64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch amd64 charlesdburton/grillbernetes-pub-hub:latest charlesdburton/grillbernetes-pub-hub:amd64
      - name: Push Manifest
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push charlesdburton/grillbernetes-pub-hub:latest
  auth-service-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of auth-service
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        working-directory: auth-service
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-auth-service:arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-auth-service:arm
  auth-service-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of auth-service
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        working-directory: auth-service
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-auth-service:arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-auth-service:arm64
  auth-service-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of auth-service
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        working-directory: auth-service
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-auth-service:amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-auth-service:amd64
  auth-service-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push
    needs: ["auth-service-build-arm", "auth-service-build-arm64", "auth-service-build-amd64"]
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create charlesdburton/grillbernetes-auth-service:latest \
          charlesdburton/grillbernetes-auth-service:amd64 \
          charlesdburton/grillbernetes-auth-service:arm \
          charlesdburton/grillbernetes-auth-service:arm64 
      - name: Annotate Arm
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm charlesdburton/grillbernetes-auth-service:latest charlesdburton/grillbernetes-auth-service:arm
      - name: Annotate Arm64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm64 charlesdburton/grillbernetes-auth-service:latest charlesdburton/grillbernetes-auth-service:arm64
      - name: Annotate AMD64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch amd64 charlesdburton/grillbernetes-auth-service:latest charlesdburton/grillbernetes-auth-service:amd64
      - name: Push Manifest
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push charlesdburton/grillbernetes-auth-service:latest
  control-hub-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of control-hub
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        working-directory: control-hub
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-control-hub:arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-control-hub:arm
  control-hub-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of control-hub
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        working-directory: control-hub
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-control-hub:arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-control-hub:arm64
  control-hub-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of control-hub
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        working-directory: control-hub
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-control-hub:amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-control-hub:amd64
  control-hub-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push
    needs: ["control-hub-build-arm", "control-hub-build-arm64", "control-hub-build-amd64"]
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create charlesdburton/grillbernetes-control-hub:latest \
          charlesdburton/grillbernetes-control-hub:amd64 \
          charlesdburton/grillbernetes-control-hub:arm \
          charlesdburton/grillbernetes-control-hub:arm64 
      - name: Annotate Arm
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm charlesdburton/grillbernetes-control-hub:latest charlesdburton/grillbernetes-control-hub:arm
      - name: Annotate Arm64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm64 charlesdburton/grillbernetes-control-hub:latest charlesdburton/grillbernetes-control-hub:arm64
      - name: Annotate AMD64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch amd64 charlesdburton/grillbernetes-control-hub:latest charlesdburton/grillbernetes-control-hub:amd64
      - name: Push Manifest
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push charlesdburton/grillbernetes-control-hub:latest
  events-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of events
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        working-directory: events
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-events:arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-events:arm
  events-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of events
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        working-directory: events
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-events:arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-events:arm64
  events-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of events
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        working-directory: events
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-events:amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-events:amd64
  events-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push
    needs: ["events-build-arm", "events-build-arm64", "events-build-amd64"]
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create charlesdburton/grillbernetes-events:latest \
          charlesdburton/grillbernetes-events:amd64 \
          charlesdburton/grillbernetes-events:arm \
          charlesdburton/grillbernetes-events:arm64 
      - name: Annotate Arm
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm charlesdburton/grillbernetes-events:latest charlesdburton/grillbernetes-events:arm
      - name: Annotate Arm64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm64 charlesdburton/grillbernetes-events:latest charlesdburton/grillbernetes-events:arm64
      - name: Annotate AMD64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch amd64 charlesdburton/grillbernetes-events:latest charlesdburton/grillbernetes-events:amd64
      - name: Push Manifest
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push charlesdburton/grillbernetes-events:latest

