name: GrillbernetesBuild

on:
  push:
    branches:
    - master

jobs:
  build-events:
    strategy:
      matrix:
        arch: ["arm64", "arm", "amd64"]
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    - name: Build Events
      env:
        DOCKER_CLI_EXPERIMENTAL: "enabled"
      run: cd events && docker build . --file Dockerfile --build-arg GOARCH=${{ matrix.arch }} -t ${{ secrets.DOCKER_USERNAME }}/grillbernetes-events:${{ matrix.arch }}
    - name: Push Events
      env:
        DOCKER_CLI_EXPERIMENTAL: "enabled"
      run: docker push ${{ secrets.DOCKER_USERNAME }}/grillbernetes-events:${{ matrix.arch }}
  build-manifest:
    needs: [build-events]
    steps:
    - uses: actions/checkout@v1
    - name: Create Manifest
      env:
        DOCKER_CLI_EXPERIMENTAL: "enabled"
      run: docker manifest create --amend ${{ secrets.DOCKER_USERNAME }}/grillbernetes-events ${{ secrets.DOCKER_USERNAME }}/grillbernetes-events:amd64 ${{ secrets.DOCKER_USERNAME }}/grillbernetes-events:arm64 ${{ secrets.DOCKER_USERNAME }}/grillbernetes-events:arm
  upload-manifest:
    needs: [build-manifest]
    steps:
    - uses: actions/checkout@v1
    - name: Push Manifest
      env:
        DOCKER_CLI_EXPERIMENTAL: "enabled"
      run: docker manifest push charlesdburton/grillbernetes-events
      
