name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: cd events && docker build . --file Dockerfile --tag my-image-name:$(date +%s)
