
name: EventsBuild

on:
  push:
    paths:
    - 'events/**.go'
    - 'events/Dockerfile'
    branches:
    - master

jobs:
  events-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of events
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        working-directory: events
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-events:arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-events:arm
  events-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of events
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        working-directory: events
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-events:arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-events:arm64
  events-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of events
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        working-directory: events
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-events:amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-events:amd64
  events-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push
    needs: ["events-build-arm", "events-build-arm64", "events-build-amd64"]
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create charlesdburton/grillbernetes-events:${{ github.sha }} \
          charlesdburton/grillbernetes-events:amd64 \
          charlesdburton/grillbernetes-events:arm \
          charlesdburton/grillbernetes-events:arm64 
      - name: Annotate Arm
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm charlesdburton/grillbernetes-events:${{ github.sha }} charlesdburton/grillbernetes-events:arm
      - name: Annotate Arm64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm64 charlesdburton/grillbernetes-events:${{ github.sha }} charlesdburton/grillbernetes-events:arm64
      - name: Annotate AMD64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch amd64 charlesdburton/grillbernetes-events:${{ github.sha }} charlesdburton/grillbernetes-events:amd64
      - name: Push Manifest
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push charlesdburton/grillbernetes-events:${{ github.sha }}
  events-kustomize:
    name: Events-Kustomize
    runs-on: ubuntu-latest
    needs: ["events-build-manifest"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.9.1"
      - name: Edit Kustomize
        run: |
          cd argocd
          kustomize edit set image charlesdburton/grillbernetes-events:latest=charlesdburton/grillbernetes-events:${{ github.sha }}
          cat kustomization.yaml

