name: PubHubBuild

on:
  push:
    branches:
      - master
    paths-ignore:
      - "argocd/**"

jobs:
  pub-hub-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of pub-hub
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        working-directory: pub-hub
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-pub-hub:arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-pub-hub:arm
  pub-hub-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of pub-hub
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        working-directory: pub-hub
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-pub-hub:arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-pub-hub:arm64
  pub-hub-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of pub-hub
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        working-directory: pub-hub
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/grillbernetes-pub-hub:amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/grillbernetes-pub-hub:amd64
  pub-hub-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push
    needs: ["pub-hub-build-arm", "pub-hub-build-arm64", "pub-hub-build-amd64"]
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create charlesdburton/grillbernetes-pub-hub:${{ github.sha }} \
          charlesdburton/grillbernetes-pub-hub:amd64 \
          charlesdburton/grillbernetes-pub-hub:arm \
          charlesdburton/grillbernetes-pub-hub:arm64 
      - name: Annotate Arm
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm charlesdburton/grillbernetes-pub-hub:${{ github.sha }} charlesdburton/grillbernetes-pub-hub:arm
      - name: Annotate Arm64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm64 charlesdburton/grillbernetes-pub-hub:${{ github.sha }} charlesdburton/grillbernetes-pub-hub:arm64
      - name: Annotate AMD64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch amd64 charlesdburton/grillbernetes-pub-hub:${{ github.sha }} charlesdburton/grillbernetes-pub-hub:amd64
      - name: Push Manifest
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push charlesdburton/grillbernetes-pub-hub:${{ github.sha }}
  